spring:
  application:
    name: all-in-market
  sql:
    init:
      mode: never
  datasource: # 환경 변수가 설정되어 있으면 그 값을 쓰고, 없으면 기본값을 쓴다.
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:allinmarket}?reWriteBatchedInserts=true
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:validate}
    show-sql: ${SPRING_JPA_SHOW_SQL:true}
    properties:
      hibernate:
        format_sql: ${HIBERNATE_FORMAT_SQL:true}
        dialect: org.hibernate.dialect.PostgreSQLDialect
#    defer-datasource-initialization: true

  autoconfigure:
    exclude:
      - org.springframework.boot.kafka.autoconfigure.KafkaAutoConfiguration

  flyway:
    enabled: true
    locations: classpath:db/migration

management:
  endpoints:
    web:
      exposure:
        include: health

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:3600000} # 1시간

server:
  port: 8080

seller:
  email: ${SELLER_ID}
  password: ${SELLER_PASSWORD}

app:
  init:
    admin:
      enabled: false

notification:
  auth:
    client-id: ${CUSTOMER_SERVER}
    secret: ${SERVER_SECRET_KEY}

