spring:
  application:
    name: all-in-market
  sql:
    init:
      mode: never
  datasource: # 환경 변수가 설정되어 있으면 그 값을 쓰고, 없으면 기본값을 쓴다.
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:allinmarket}?reWriteBatchedInserts=true
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:validate}
    show-sql: ${SPRING_JPA_SHOW_SQL:true}
    properties:
      hibernate:
        format_sql: ${HIBERNATE_FORMAT_SQL:true}
        dialect: org.hibernate.dialect.PostgreSQLDialect
#    defer-datasource-initialization: true

  autoconfigure:
    exclude:
      - org.springframework.boot.kafka.autoconfigure.KafkaAutoConfiguration

  flyway:
    enabled: true
    locations: classpath:db/migration

  cloud:
    aws:
      region:
        static: ap-northeast-2
      cloudwatch:
        enabled: ${CLOUDWATCH_METRICS_ENABLED:false}
  # 가상 스레드 적용
  threads:
    virtual:
      enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

  endpoint:
    health:
      show-details: never

  # 생성되는 metrics에 어디서 발생한 metrics인지 tag 부착
  # 아래 3개 dimension은 모든 Metric에 공통적으로 붙여짐
  metrics:
    tags:
      application: ${spring.application.name}
      environment: ${SPRING_PROFILES_ACTIVE:local}
      service: ${APP_SERVICE_NAME:customer}

    # http.server.requests 메트릭에 대해
    # p95 latency 계산 + histogram 생성
    # histogram: 응답시간 데이터를 구간별로 묶어줌 (0~100ms 구간, 100~500ms 구간 ...)
    distribution:
      percentiles:
        http.server.requests: 0.95
      percentiles-histogram:
        http.server.requests: true

  # Micrometer 메트릭을 CloudWatch Metrics로 어떻게 보낼지 설정
  cloudwatch:
    metrics:
      export:
        enabled: ${CLOUDWATCH_METRICS_ENABLED:true}
        namespace: ${CLOUDWATCH_METRICS_NAMESPACE:all-in-market/dev/ApplicationMetrics}
        step: 60s

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:3600000} # 1시간

server:
  port: 8080

seller:
  email: ${SELLER_ID}
  password: ${SELLER_PASSWORD}

app:
  init:
    admin:
      enabled: false

notification:
  auth:
    client-id: ${CUSTOMER_SERVER}
    secret: ${SERVER_SECRET_KEY}
