{
 "title": "all-in-market",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Customer Average RPS Per Minute",
   "type": "timeseries",
   "description": "Average HTTP Requests Per Second (RPS) over the Last 1 Minute",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{service=\"customer\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Customer Requests by Status",
   "type": "timeseries",
   "description": "HTTP Request Count by Status Code over the Last 5 Minutes",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (status) (\r\n  increase(http_server_requests_seconds_count{service=\"customer\"}[5m])\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Customer API p95 Latency",
   "type": "timeseries",
   "description": "P95 response time for all customer APIs (excluding UNKNOWN URIs)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.95,\r\n  sum by (le) (\r\n    rate(http_server_requests_seconds_bucket{\r\n      service=\"customer\",\r\n      uri!=\"UNKNOWN\"\r\n    }[5m])\r\n  )\r\n)",
     "legendFormat": "p95 latency"
    }
   ]
  },
  {
   "title": "Customer Error Requests by URI",
   "type": "timeseries",
   "description": "4xx/5xx Error Request Count by URI and Status Code over the Last 5 Minutes\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by (status, uri) (\r\n  increase(http_server_requests_seconds_count{\r\n    service=\"customer\",\r\n    outcome=~\"CLIENT_ERROR|SERVER_ERROR\",\r\n    uri!=\"UNKNOWN\"\r\n  }[5m])\r\n)",
     "legendFormat": "{{status}} {{uri}}"
    }
   ]
  },
  {
   "title": "Customer HikariCP Connection Pool Status",
   "type": "timeseries",
   "description": "Shows active, total, and maximum DB connections in the HikariCP connection pool.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(hikaricp_connections_active{\r\n  service=\"customer\"\r\n})",
     "legendFormat": "Active DB Connections"
    },
    {
     "expr": "sum(hikaricp_connections_max{\r\n  service=\"customer\"\r\n})",
     "legendFormat": "Max DB Connections"
    },
    {
     "expr": "sum(hikaricp_connections{\r\n  service=\"customer\"\r\n})",
     "legendFormat": "Total DB Connections"
    }
   ]
  },
  {
   "title": "Customer JVM Heap Memory",
   "type": "timeseries",
   "description": "Current JVM heap memory usage, committed heap size, and maximum allowed heap size for the customer service.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{service=\"customer\", area=\"heap\"}) ",
     "legendFormat": "Heap Used"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{service=\"customer\", area=\"heap\"})",
     "legendFormat": "Heap Committed"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{service=\"customer\", area=\"heap\"})",
     "legendFormat": "Heap Max"
    }
   ]
  }
 ]
}