create table admins (
                        id bigint generated by default as identity,
                        created_at timestamp(6) not null,
                        updated_at timestamp(6) not null,
                        deleted_at timestamp(6),
                        email varchar(100) not null,
                        name varchar(50) not null,
                        password varchar(255) not null,
                        role varchar(20) not null check ((role in ('BUYER','SELLER','ADMIN'))),
                        primary key (id)
)