create table restock_subscriptions(
    id bigint generated by default as identity primary key,
    user_id bigint not null,
    product_id bigint not null,
    status character varying(255) not null,
    created_at timestamp(6) not null,
    updated_at timestamp(6) not null,
    last_notified_at timestamp(6),
    constraint uk_restock_subscriptions_buyer UNIQUE (user_id, product_id)
);