CREATE TABLE payouts (
                         id bigint GENERATED BY DEFAULT AS IDENTITY,
                         created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
                         seller_id bigint NOT NULL,
                         settlement_id bigint NOT NULL,
                         amount numeric(12,2) NOT NULL,
                         fee numeric(12,2) NOT NULL,
                         status varchar(20) NOT NULL,
                         payout_key varchar(255) NOT NULL,
                         processed_at TIMESTAMP(6) WITH TIME ZONE,
                         retry_count int NOT NULL DEFAULT 0,

                         CONSTRAINT pk_payouts PRIMARY KEY (id),
                         CONSTRAINT fk_payout_seller FOREIGN KEY (seller_id) REFERENCES sellers(id),
                         CONSTRAINT uk_payout_settlement_id UNIQUE (settlement_id),
                         CONSTRAINT uk_payout_payout_key UNIQUE (payout_key)
);

-- 인덱스 추가 (조회 성능 향상)
CREATE INDEX idx_payouts_status ON payouts (status);

-- Sellers 테이블 bank_code 추가
ALTER TABLE sellers ADD COLUMN bank_code varchar(30) NOT NULL;
