CREATE TABLE restock_notifications
(
    id         BIGINT generated by default as identity PRIMARY KEY,
    user_id    BIGINT       NOT NULL,
    product_id BIGINT       NOT NULL,
    message    VARCHAR(255) NOT NULL,
    is_read    BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CREATE INDEX idx_restock_notifications_user_created_at ON restock_notifications (user_id, created_at DESC)
);
