create table order_status_update_notifications
(
    id bigint generated by default as identity primary key,
    user_id bigint not null,
    order_id bigint not null,
    status varchar(255) not null,
    message varchar(255) not null,
    is_read boolean not null default false,
    created_at timestamp not null default CURRENT_TIMESTAMP,
    updated_at timestamp not null default CURRENT_TIMESTAMP,
    constraint fk_order_status_update_notifications_user foreign key(user_id) references users(id),
    constraint fk_order_status_update_notifications_order foreign key (order_id) references orders(id)
);