CREATE TABLE addresses
(
    is_default boolean                NOT NULL,
    buyer_id   bigint                 NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    id         bigint                 NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    phone      character varying(20)  NOT NULL,
    recipient  character varying(50)  NOT NULL,
    detail     character varying(100) NOT NULL
);

ALTER TABLE addresses ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME addresses_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE buyers
(
    created_at timestamp(6) without time zone NOT NULL,
    deleted_at timestamp(6) without time zone,
    id         bigint                 NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    phone      character varying(20)  NOT NULL,
    role       character varying(20)  NOT NULL,
    name       character varying(50)  NOT NULL,
    email      character varying(100) NOT NULL,
    password   character varying(255) NOT NULL,
    CONSTRAINT buyers_role_check CHECK (((role)::text = ANY ((ARRAY['BUYER':: character varying, 'SELLER':: character varying])::text[])))
);

ALTER TABLE buyers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME buyers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE cart_items
(
    quantity   integer NOT NULL,
    cart_id    bigint  NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    id         bigint  NOT NULL,
    product_id bigint  NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL
);

ALTER TABLE cart_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME cart_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE carts
(
    buyer_id   bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    id         bigint NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL
);

ALTER TABLE carts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME carts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE categories
(
    sort_order integer,
    created_at timestamp(6) without time zone NOT NULL,
    deleted_at timestamp(6) without time zone,
    id         bigint                NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    name       character varying(50) NOT NULL
);

ALTER TABLE categories ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME categories_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE order_items
(
    quantity     integer                NOT NULL,
    unit_price   numeric(12, 2)         NOT NULL,
    created_at   timestamp(6) without time zone NOT NULL,
    id           bigint                 NOT NULL,
    order_id     bigint                 NOT NULL,
    product_id   bigint                 NOT NULL,
    seller_id    bigint                 NOT NULL,
    updated_at   timestamp(6) without time zone NOT NULL,
    product_name character varying(200) NOT NULL
);

ALTER TABLE order_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME order_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE orders
(
    total_amount    numeric(12, 2)         NOT NULL,
    buyer_id        bigint                 NOT NULL,
    created_at      timestamp(6) without time zone NOT NULL,
    id              bigint                 NOT NULL,
    updated_at      timestamp(6) without time zone NOT NULL,
    phone           character varying(20)  NOT NULL,
    status          character varying(20)  NOT NULL,
    recipient       character varying(50)  NOT NULL,
    tracking_number character varying(50),
    address         character varying(255) NOT NULL,
    CONSTRAINT orders_status_check CHECK (((status)::text = ANY ((ARRAY['CREATED':: character varying, 'PAID':: character varying, 'SHIPPED':: character varying, 'DELIVERED':: character varying, 'REFUNDED':: character varying, 'FAILED':: character varying])::text[])))
);

ALTER TABLE orders ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME orders_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE payments
(
    amount     numeric(12, 2)         NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    id         bigint                 NOT NULL,
    order_id   bigint                 NOT NULL,
    paid_at    timestamp(6) without time zone,
    updated_at timestamp(6) without time zone NOT NULL,
    version    bigint,
    method     character varying(20)  NOT NULL,
    imp_uid    character varying(255) NOT NULL,
    status     character varying(255) NOT NULL,
    CONSTRAINT payments_method_check CHECK (((method)::text = ANY ((ARRAY['MOCK':: character varying, 'TOSS':: character varying, 'KAKAO':: character varying])::text[]))),
    CONSTRAINT payments_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'SUCCESS'::character varying, 'FAILED'::character varying, 'REFUNDED'::character varying])::text[])))
);

ALTER TABLE payments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME payments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE products
(
    price       numeric(12, 2)         NOT NULL,
    stock       integer                NOT NULL,
    category_id bigint                 NOT NULL,
    created_at  timestamp(6) without time zone NOT NULL,
    deleted_at  timestamp(6) without time zone,
    id          bigint                 NOT NULL,
    seller_id   bigint                 NOT NULL,
    updated_at  timestamp(6) without time zone NOT NULL,
    status      character varying(20)  NOT NULL,
    name        character varying(200) NOT NULL,
    description character varying(255) NOT NULL,
    CONSTRAINT products_status_check CHECK (((status)::text = ANY ((ARRAY['ON_SALE':: character varying, 'HIDDEN':: character varying])::text[])))
);

ALTER TABLE products ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME products_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE refunds
(
    buyer_id      bigint                NOT NULL,
    created_at    timestamp(6) without time zone NOT NULL,
    id            bigint                NOT NULL,
    payment_id    bigint                NOT NULL,
    processed_at  timestamp(6) without time zone,
    updated_at    timestamp(6) without time zone NOT NULL,
    version       bigint                NOT NULL,
    status        character varying(20) NOT NULL,
    reason        character varying(50) NOT NULL,
    denied_reason character varying(255),
    description   character varying(255),
    CONSTRAINT refunds_reason_check CHECK (((reason)::text = ANY ((ARRAY['CHANGE_OF_MIND':: character varying, 'WRONG_ITEM':: character varying, 'DAMAGED':: character varying, 'PAYMENT_AMOUNT_MISMATCH':: character varying])::text[]))),
    CONSTRAINT refunds_status_check CHECK (((status)::text = ANY ((ARRAY['NONE'::character varying, 'PENDING'::character varying, 'SUCCESS'::character varying, 'FAILED'::character varying, 'DENIED'::character varying])::text[])))
);

ALTER TABLE refunds ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME refunds_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE seller_daily_statistics
(
    net_sales     numeric(12, 2) NOT NULL,
    refund_amount numeric(12, 2) NOT NULL,
    stat_date     date           NOT NULL,
    total_items   integer,
    total_orders  integer,
    total_refunds integer,
    total_sales   numeric(12, 2) NOT NULL,
    created_at    timestamp(6) without time zone NOT NULL,
    id            bigint         NOT NULL,
    seller_id     bigint         NOT NULL
);

ALTER TABLE seller_daily_statistics ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME seller_daily_statistics_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE sellers
(
    created_at   timestamp(6) without time zone NOT NULL,
    deleted_at   timestamp(6) without time zone,
    id           bigint                 NOT NULL,
    updated_at   timestamp(6) without time zone NOT NULL,
    biz_number   character varying(20)  NOT NULL,
    phone        character varying(20)  NOT NULL,
    role         character varying(20)  NOT NULL,
    status       character varying(20)  NOT NULL,
    bank_account character varying(50)  NOT NULL,
    name         character varying(50)  NOT NULL,
    email        character varying(100) NOT NULL,
    store_name   character varying(100) NOT NULL,
    password     character varying(255) NOT NULL,
    CONSTRAINT sellers_role_check CHECK (((role)::text = ANY ((ARRAY['BUYER':: character varying, 'SELLER':: character varying])::text[]))),
    CONSTRAINT sellers_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'APPROVED'::character varying, 'REJECTED'::character varying])::text[])))
);

ALTER TABLE sellers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME sellers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE settlements
(
    amount       numeric(12, 2)        NOT NULL,
    fee          numeric(12, 2)        NOT NULL,
    period_end   date                  NOT NULL,
    period_start date                  NOT NULL,
    completed_at timestamp(6) without time zone,
    created_at   timestamp(6) without time zone NOT NULL,
    id           bigint                NOT NULL,
    seller_id    bigint                NOT NULL,
    updated_at   timestamp(6) without time zone NOT NULL,
    status       character varying(20) NOT NULL,
    type         character varying(20) NOT NULL,
    CONSTRAINT settlements_status_check CHECK (((status)::text = ANY ((ARRAY['FAILED':: character varying, 'COMPLETED':: character varying])::text[]))),
    CONSTRAINT settlements_type_check CHECK (((type)::text = ANY ((ARRAY['MID'::character varying, 'END'::character varying])::text[])))
);

ALTER TABLE settlements ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME settlements_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE transaction_histories
(
    amount         numeric(12, 2)         NOT NULL,
    created_at     timestamp(6) without time zone NOT NULL,
    id             bigint                 NOT NULL,
    transaction_id bigint                 NOT NULL,
    payment_status character varying(255) NOT NULL,
    refund_status  character varying(255) NOT NULL,
    type           character varying(255) NOT NULL,
    CONSTRAINT transaction_histories_payment_status_check CHECK (((payment_status)::text = ANY ((ARRAY['PENDING':: character varying, 'SUCCESS':: character varying, 'FAILED':: character varying, 'REFUNDED':: character varying])::text[]))),
    CONSTRAINT transaction_histories_refund_status_check CHECK (((refund_status)::text = ANY ((ARRAY['NONE'::character varying, 'PENDING'::character varying, 'SUCCESS'::character varying, 'FAILED'::character varying, 'DENIED'::character varying])::text[]))),
    CONSTRAINT transaction_histories_type_check CHECK (((type)::text = ANY ((ARRAY['PAYMENT'::character varying, 'REFUND'::character varying])::text[])))
);

ALTER TABLE transaction_histories ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME transaction_histories_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY addresses
    ADD CONSTRAINT addresses_pkey PRIMARY KEY (id);

ALTER TABLE ONLY buyers
    ADD CONSTRAINT buyers_email_key UNIQUE (email);

ALTER TABLE ONLY buyers
    ADD CONSTRAINT buyers_pkey PRIMARY KEY (id);

ALTER TABLE ONLY cart_items
    ADD CONSTRAINT cart_items_pkey PRIMARY KEY (id);

ALTER TABLE ONLY carts
    ADD CONSTRAINT carts_buyer_id_key UNIQUE (buyer_id);

ALTER TABLE ONLY carts
    ADD CONSTRAINT carts_pkey PRIMARY KEY (id);

ALTER TABLE ONLY categories
    ADD CONSTRAINT categories_name_key UNIQUE (name);

ALTER TABLE ONLY categories
    ADD CONSTRAINT categories_pkey PRIMARY KEY (id);

ALTER TABLE ONLY order_items
    ADD CONSTRAINT order_items_pkey PRIMARY KEY (id);

ALTER TABLE ONLY orders
    ADD CONSTRAINT orders_pkey PRIMARY KEY (id);

ALTER TABLE ONLY payments
    ADD CONSTRAINT payments_imp_uid_key UNIQUE (imp_uid);

ALTER TABLE ONLY payments
    ADD CONSTRAINT payments_pkey PRIMARY KEY (id);

ALTER TABLE ONLY products
    ADD CONSTRAINT products_pkey PRIMARY KEY (id);

ALTER TABLE ONLY refunds
    ADD CONSTRAINT refunds_payment_id_key UNIQUE (payment_id);

ALTER TABLE ONLY refunds
    ADD CONSTRAINT refunds_pkey PRIMARY KEY (id);

ALTER TABLE ONLY seller_daily_statistics
    ADD CONSTRAINT seller_daily_statistics_pkey PRIMARY KEY (id);

ALTER TABLE ONLY sellers
    ADD CONSTRAINT sellers_biz_number_key UNIQUE (biz_number);

ALTER TABLE ONLY sellers
    ADD CONSTRAINT sellers_email_key UNIQUE (email);

ALTER TABLE ONLY sellers
    ADD CONSTRAINT sellers_pkey PRIMARY KEY (id);

ALTER TABLE ONLY settlements
    ADD CONSTRAINT settlements_pkey PRIMARY KEY (id);

ALTER TABLE ONLY transaction_histories
    ADD CONSTRAINT transaction_histories_pkey PRIMARY KEY (id);

ALTER TABLE ONLY seller_daily_statistics
    ADD CONSTRAINT uk_seller_stat_date UNIQUE (seller_id, stat_date);

ALTER TABLE ONLY order_items
    ADD CONSTRAINT fk_order_items_seller FOREIGN KEY (seller_id) REFERENCES sellers(id);

ALTER TABLE ONLY cart_items
    ADD CONSTRAINT fk1re40cjegsfvw58xrkdp6bac6 FOREIGN KEY (product_id) REFERENCES products(id);

ALTER TABLE ONLY settlements
    ADD CONSTRAINT fk3a4cgs7utrvl2vk6egdnw624t FOREIGN KEY (seller_id) REFERENCES sellers(id);

ALTER TABLE ONLY payments
    ADD CONSTRAINT fk81gagumt0r8y3rmudcgpbk42l FOREIGN KEY (order_id) REFERENCES orders(id);

ALTER TABLE ONLY order_items
    ADD CONSTRAINT fkbioxgbv59vetrxe0ejfubep1w FOREIGN KEY (order_id) REFERENCES orders(id);

ALTER TABLE ONLY products
    ADD CONSTRAINT fkepbha8uixgrmnejm27n6e1kkd FOREIGN KEY (seller_id) REFERENCES sellers(id);

ALTER TABLE ONLY refunds
    ADD CONSTRAINT fkj23mldknhmi6aok0w7s5mw4fq FOREIGN KEY (buyer_id) REFERENCES buyers(id);

ALTER TABLE ONLY orders
    ADD CONSTRAINT fkm64p5iuhw3kaqel7x21pskgjr FOREIGN KEY (buyer_id) REFERENCES buyers(id);

ALTER TABLE ONLY seller_daily_statistics
    ADD CONSTRAINT fkm9s5okhl9n7qek3cpv4pxdyyf FOREIGN KEY (seller_id) REFERENCES sellers(id);

ALTER TABLE ONLY order_items
    ADD CONSTRAINT fkocimc7dtr037rh4ls4l95nlfi FOREIGN KEY (product_id) REFERENCES products(id);

ALTER TABLE ONLY products
    ADD CONSTRAINT fkog2rp4qthbtt2lfyhfo32lsw9 FOREIGN KEY (category_id) REFERENCES categories(id);

ALTER TABLE ONLY addresses
    ADD CONSTRAINT fkp2p0gwrvy9h6kd3m9yn8338f FOREIGN KEY (buyer_id) REFERENCES buyers(id);

ALTER TABLE ONLY cart_items
    ADD CONSTRAINT fkpcttvuq4mxppo8sxggjtn5i2c FOREIGN KEY (cart_id) REFERENCES carts(id);

ALTER TABLE ONLY refunds
    ADD CONSTRAINT fkpt9ic0j1y6xwlej99wnynvnpy FOREIGN KEY (payment_id) REFERENCES payments(id);

ALTER TABLE ONLY carts
    ADD CONSTRAINT fkq7d257fhb4gyhk7ova36w0ga4 FOREIGN KEY (buyer_id) REFERENCES buyers(id);
