--
-- PostgreSQL database dump
--

-- Dumped from database version 17.9 (Debian 17.9-1.pgdg12+1)
-- Dumped by pg_dump version 17.9 (Debian 17.9-1.pgdg12+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;
SET default_tablespace = '';
SET default_table_access_method = heap;

--
-- Name: addresses; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.addresses
(
    is_default boolean                NOT NULL,
    buyer_id   bigint                 NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    id         bigint                 NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    phone      character varying(20)  NOT NULL,
    recipient  character varying(50)  NOT NULL,
    detail     character varying(100) NOT NULL
);


--
-- Name: addresses_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.addresses ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.addresses_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: buyers; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.buyers
(
    created_at timestamp(6) without time zone NOT NULL,
    deleted_at timestamp(6) without time zone,
    id         bigint                 NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    phone      character varying(20)  NOT NULL,
    role       character varying(20)  NOT NULL,
    name       character varying(50)  NOT NULL,
    email      character varying(100) NOT NULL,
    password   character varying(255) NOT NULL,
    CONSTRAINT buyers_role_check CHECK (((role)::text = ANY ((ARRAY['BUYER':: character varying, 'SELLER':: character varying])::text[])
) )
);


--
-- Name: buyers_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.buyers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.buyers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cart_items; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.cart_items
(
    quantity   integer NOT NULL,
    cart_id    bigint  NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    id         bigint  NOT NULL,
    product_id bigint  NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL
);


--
-- Name: cart_items_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.cart_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cart_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: carts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.carts
(
    buyer_id   bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    id         bigint NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL
);


--
-- Name: carts_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.carts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.carts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: categories; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.categories
(
    sort_order integer,
    created_at timestamp(6) without time zone NOT NULL,
    deleted_at timestamp(6) without time zone,
    id         bigint                NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    name       character varying(50) NOT NULL
);


--
-- Name: categories_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.categories ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.categories_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: order_items; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.order_items
(
    quantity     integer                NOT NULL,
    unit_price   numeric(12, 2)         NOT NULL,
    created_at   timestamp(6) without time zone NOT NULL,
    id           bigint                 NOT NULL,
    order_id     bigint                 NOT NULL,
    product_id   bigint                 NOT NULL,
    seller_id    bigint                 NOT NULL,
    updated_at   timestamp(6) without time zone NOT NULL,
    product_name character varying(200) NOT NULL
);


--
-- Name: order_items_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.order_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.order_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: orders; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.orders
(
    total_amount    numeric(12, 2)         NOT NULL,
    buyer_id        bigint                 NOT NULL,
    created_at      timestamp(6) without time zone NOT NULL,
    id              bigint                 NOT NULL,
    updated_at      timestamp(6) without time zone NOT NULL,
    phone           character varying(20)  NOT NULL,
    status          character varying(20)  NOT NULL,
    recipient       character varying(50)  NOT NULL,
    tracking_number character varying(50),
    address         character varying(255) NOT NULL,
    CONSTRAINT orders_status_check CHECK (((status)::text = ANY ((ARRAY['CREATED':: character varying, 'PAID':: character varying, 'SHIPPED':: character varying, 'DELIVERED':: character varying, 'REFUNDED':: character varying, 'FAILED':: character varying])::text[])
) )
);


--
-- Name: orders_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.orders ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.orders_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: payments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.payments
(
    amount     numeric(12, 2)         NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    id         bigint                 NOT NULL,
    order_id   bigint                 NOT NULL,
    paid_at    timestamp(6) without time zone,
    updated_at timestamp(6) without time zone NOT NULL,
    version    bigint,
    method     character varying(20)  NOT NULL,
    imp_uid    character varying(255) NOT NULL,
    status     character varying(255) NOT NULL,
    CONSTRAINT payments_method_check CHECK (((method)::text = ANY ((ARRAY['MOCK':: character varying, 'TOSS':: character varying, 'KAKAO':: character varying])::text[])
) ),
    CONSTRAINT payments_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'SUCCESS'::character varying, 'FAILED'::character varying, 'REFUNDED'::character varying])::text[])))
);


--
-- Name: payments_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.payments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.payments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: products; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.products
(
    price       numeric(12, 2)         NOT NULL,
    stock       integer                NOT NULL,
    category_id bigint                 NOT NULL,
    created_at  timestamp(6) without time zone NOT NULL,
    deleted_at  timestamp(6) without time zone,
    id          bigint                 NOT NULL,
    seller_id   bigint                 NOT NULL,
    updated_at  timestamp(6) without time zone NOT NULL,
    status      character varying(20)  NOT NULL,
    name        character varying(200) NOT NULL,
    description character varying(255) NOT NULL,
    CONSTRAINT products_status_check CHECK (((status)::text = ANY ((ARRAY['ON_SALE':: character varying, 'HIDDEN':: character varying])::text[])
) )
);


--
-- Name: products_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.products ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.products_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: refunds; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.refunds
(
    buyer_id      bigint                NOT NULL,
    created_at    timestamp(6) without time zone NOT NULL,
    id            bigint                NOT NULL,
    payment_id    bigint                NOT NULL,
    processed_at  timestamp(6) without time zone,
    updated_at    timestamp(6) without time zone NOT NULL,
    version       bigint                NOT NULL,
    status        character varying(20) NOT NULL,
    reason        character varying(50) NOT NULL,
    denied_reason character varying(255),
    description   character varying(255),
    CONSTRAINT refunds_reason_check CHECK (((reason)::text = ANY ((ARRAY['CHANGE_OF_MIND':: character varying, 'WRONG_ITEM':: character varying, 'DAMAGED':: character varying, 'PAYMENT_AMOUNT_MISMATCH':: character varying])::text[])
) ),
    CONSTRAINT refunds_status_check CHECK (((status)::text = ANY ((ARRAY['NONE'::character varying, 'PENDING'::character varying, 'SUCCESS'::character varying, 'FAILED'::character varying, 'DENIED'::character varying])::text[])))
);


--
-- Name: refunds_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.refunds ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.refunds_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: seller_daily_statistics; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.seller_daily_statistics
(
    net_sales     numeric(12, 2) NOT NULL,
    refund_amount numeric(12, 2) NOT NULL,
    stat_date     date           NOT NULL,
    total_items   integer,
    total_orders  integer,
    total_refunds integer,
    total_sales   numeric(12, 2) NOT NULL,
    created_at    timestamp(6) without time zone NOT NULL,
    id            bigint         NOT NULL,
    seller_id     bigint         NOT NULL
);


--
-- Name: seller_daily_statistics_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.seller_daily_statistics ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.seller_daily_statistics_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sellers; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sellers
(
    created_at   timestamp(6) without time zone NOT NULL,
    deleted_at   timestamp(6) without time zone,
    id           bigint                 NOT NULL,
    updated_at   timestamp(6) without time zone NOT NULL,
    biz_number   character varying(20)  NOT NULL,
    phone        character varying(20)  NOT NULL,
    role         character varying(20)  NOT NULL,
    status       character varying(20)  NOT NULL,
    bank_account character varying(50)  NOT NULL,
    name         character varying(50)  NOT NULL,
    email        character varying(100) NOT NULL,
    store_name   character varying(100) NOT NULL,
    password     character varying(255) NOT NULL,
    CONSTRAINT sellers_role_check CHECK (((role)::text = ANY ((ARRAY['BUYER':: character varying, 'SELLER':: character varying])::text[])
) ),
    CONSTRAINT sellers_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'APPROVED'::character varying, 'REJECTED'::character varying])::text[])))
);


--
-- Name: sellers_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.sellers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sellers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: settlements; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.settlements
(
    amount       numeric(12, 2)        NOT NULL,
    fee          numeric(12, 2)        NOT NULL,
    period_end   date                  NOT NULL,
    period_start date                  NOT NULL,
    completed_at timestamp(6) without time zone,
    created_at   timestamp(6) without time zone NOT NULL,
    id           bigint                NOT NULL,
    seller_id    bigint                NOT NULL,
    updated_at   timestamp(6) without time zone NOT NULL,
    status       character varying(20) NOT NULL,
    type         character varying(20) NOT NULL,
    CONSTRAINT settlements_status_check CHECK (((status)::text = ANY ((ARRAY['FAILED':: character varying, 'COMPLETED':: character varying])::text[])
) ),
    CONSTRAINT settlements_type_check CHECK (((type)::text = ANY ((ARRAY['MID'::character varying, 'END'::character varying])::text[])))
);


--
-- Name: settlements_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.settlements ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.settlements_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: transaction_histories; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.transaction_histories
(
    amount         numeric(12, 2)         NOT NULL,
    created_at     timestamp(6) without time zone NOT NULL,
    id             bigint                 NOT NULL,
    transaction_id bigint                 NOT NULL,
    payment_status character varying(255) NOT NULL,
    refund_status  character varying(255) NOT NULL,
    type           character varying(255) NOT NULL,
    CONSTRAINT transaction_histories_payment_status_check CHECK (((payment_status)::text = ANY ((ARRAY['PENDING':: character varying, 'SUCCESS':: character varying, 'FAILED':: character varying, 'REFUNDED':: character varying])::text[])
) ),
    CONSTRAINT transaction_histories_refund_status_check CHECK (((refund_status)::text = ANY ((ARRAY['NONE'::character varying, 'PENDING'::character varying, 'SUCCESS'::character varying, 'FAILED'::character varying, 'DENIED'::character varying])::text[]))),
    CONSTRAINT transaction_histories_type_check CHECK (((type)::text = ANY ((ARRAY['PAYMENT'::character varying, 'REFUND'::character varying])::text[])))
);


--
-- Name: transaction_histories_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.transaction_histories ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.transaction_histories_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: addresses addresses_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.addresses
    ADD CONSTRAINT addresses_pkey PRIMARY KEY (id);


--
-- Name: buyers buyers_email_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.buyers
    ADD CONSTRAINT buyers_email_key UNIQUE (email);


--
-- Name: buyers buyers_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.buyers
    ADD CONSTRAINT buyers_pkey PRIMARY KEY (id);


--
-- Name: cart_items cart_items_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cart_items
    ADD CONSTRAINT cart_items_pkey PRIMARY KEY (id);


--
-- Name: carts carts_buyer_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.carts
    ADD CONSTRAINT carts_buyer_id_key UNIQUE (buyer_id);


--
-- Name: carts carts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.carts
    ADD CONSTRAINT carts_pkey PRIMARY KEY (id);


--
-- Name: categories categories_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.categories
    ADD CONSTRAINT categories_name_key UNIQUE (name);


--
-- Name: categories categories_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.categories
    ADD CONSTRAINT categories_pkey PRIMARY KEY (id);


--
-- Name: order_items order_items_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.order_items
    ADD CONSTRAINT order_items_pkey PRIMARY KEY (id);


--
-- Name: orders orders_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT orders_pkey PRIMARY KEY (id);


--
-- Name: payments payments_imp_uid_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT payments_imp_uid_key UNIQUE (imp_uid);


--
-- Name: payments payments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT payments_pkey PRIMARY KEY (id);


--
-- Name: products products_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT products_pkey PRIMARY KEY (id);


--
-- Name: refunds refunds_payment_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.refunds
    ADD CONSTRAINT refunds_payment_id_key UNIQUE (payment_id);


--
-- Name: refunds refunds_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.refunds
    ADD CONSTRAINT refunds_pkey PRIMARY KEY (id);


--
-- Name: seller_daily_statistics seller_daily_statistics_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.seller_daily_statistics
    ADD CONSTRAINT seller_daily_statistics_pkey PRIMARY KEY (id);


--
-- Name: sellers sellers_biz_number_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sellers
    ADD CONSTRAINT sellers_biz_number_key UNIQUE (biz_number);


--
-- Name: sellers sellers_email_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sellers
    ADD CONSTRAINT sellers_email_key UNIQUE (email);


--
-- Name: sellers sellers_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sellers
    ADD CONSTRAINT sellers_pkey PRIMARY KEY (id);


--
-- Name: settlements settlements_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.settlements
    ADD CONSTRAINT settlements_pkey PRIMARY KEY (id);


--
-- Name: transaction_histories transaction_histories_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.transaction_histories
    ADD CONSTRAINT transaction_histories_pkey PRIMARY KEY (id);


--
-- Name: seller_daily_statistics uk_seller_stat_date; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.seller_daily_statistics
    ADD CONSTRAINT uk_seller_stat_date UNIQUE (seller_id, stat_date);


--
-- Name: order_items fk122hh8jwo7aj2omj1x6vrej9s; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.order_items
    ADD CONSTRAINT fk122hh8jwo7aj2omj1x6vrej9s FOREIGN KEY (seller_id) REFERENCES public.sellers(id);


--
-- Name: cart_items fk1re40cjegsfvw58xrkdp6bac6; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cart_items
    ADD CONSTRAINT fk1re40cjegsfvw58xrkdp6bac6 FOREIGN KEY (product_id) REFERENCES public.products(id);


--
-- Name: settlements fk3a4cgs7utrvl2vk6egdnw624t; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.settlements
    ADD CONSTRAINT fk3a4cgs7utrvl2vk6egdnw624t FOREIGN KEY (seller_id) REFERENCES public.sellers(id);


--
-- Name: payments fk81gagumt0r8y3rmudcgpbk42l; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT fk81gagumt0r8y3rmudcgpbk42l FOREIGN KEY (order_id) REFERENCES public.orders(id);


--
-- Name: order_items fkbioxgbv59vetrxe0ejfubep1w; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.order_items
    ADD CONSTRAINT fkbioxgbv59vetrxe0ejfubep1w FOREIGN KEY (order_id) REFERENCES public.orders(id);


--
-- Name: products fkepbha8uixgrmnejm27n6e1kkd; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT fkepbha8uixgrmnejm27n6e1kkd FOREIGN KEY (seller_id) REFERENCES public.sellers(id);


--
-- Name: refunds fkj23mldknhmi6aok0w7s5mw4fq; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.refunds
    ADD CONSTRAINT fkj23mldknhmi6aok0w7s5mw4fq FOREIGN KEY (buyer_id) REFERENCES public.buyers(id);


--
-- Name: orders fkm64p5iuhw3kaqel7x21pskgjr; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT fkm64p5iuhw3kaqel7x21pskgjr FOREIGN KEY (buyer_id) REFERENCES public.buyers(id);


--
-- Name: seller_daily_statistics fkm9s5okhl9n7qek3cpv4pxdyyf; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.seller_daily_statistics
    ADD CONSTRAINT fkm9s5okhl9n7qek3cpv4pxdyyf FOREIGN KEY (seller_id) REFERENCES public.sellers(id);


--
-- Name: order_items fkocimc7dtr037rh4ls4l95nlfi; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.order_items
    ADD CONSTRAINT fkocimc7dtr037rh4ls4l95nlfi FOREIGN KEY (product_id) REFERENCES public.products(id);


--
-- Name: products fkog2rp4qthbtt2lfyhfo32lsw9; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT fkog2rp4qthbtt2lfyhfo32lsw9 FOREIGN KEY (category_id) REFERENCES public.categories(id);


--
-- Name: addresses fkp2p0gwrvy9h6kd3m9yn8338f; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.addresses
    ADD CONSTRAINT fkp2p0gwrvy9h6kd3m9yn8338f FOREIGN KEY (buyer_id) REFERENCES public.buyers(id);


--
-- Name: cart_items fkpcttvuq4mxppo8sxggjtn5i2c; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cart_items
    ADD CONSTRAINT fkpcttvuq4mxppo8sxggjtn5i2c FOREIGN KEY (cart_id) REFERENCES public.carts(id);


--
-- Name: refunds fkpt9ic0j1y6xwlej99wnynvnpy; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.refunds
    ADD CONSTRAINT fkpt9ic0j1y6xwlej99wnynvnpy FOREIGN KEY (payment_id) REFERENCES public.payments(id);


--
-- Name: carts fkq7d257fhb4gyhk7ova36w0ga4; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.carts
    ADD CONSTRAINT fkq7d257fhb4gyhk7ova36w0ga4 FOREIGN KEY (buyer_id) REFERENCES public.buyers(id);


--
-- PostgreSQL database dump complete
--

