CREATE TABLE seller_dashboard (
                                  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                  seller_id bigint NOT NULL,
                                  stat_date date NOT NULL,
                                  total_orders integer,
                                  total_sales numeric(12,2) NOT NULL,
                                  total_products_sold integer,
                                  total_refunds integer,
                                  refund_amount numeric(12,2) NOT NULL,
                                  fee_amount numeric(12,2) NOT NULL,
                                  settlement_amount numeric(12,2) NOT NULL,
                                  created_at timestamp(6) without time zone NOT NULL,
                                  updated_at timestamp(6) without time zone NOT NULL,
                                  CONSTRAINT uk_seller_dashboard_date UNIQUE (seller_id, stat_date),
                                  CONSTRAINT fk_seller_dashboard_seller FOREIGN KEY (seller_id) REFERENCES sellers(id)
);