CREATE TABLE dashboard_outbox
(
    id           bigint                              NOT NULL,
    event_type   character varying(255)              NOT NULL,
    aggregate_id bigint                              NOT NULL,
    payload      text                                NOT NULL,
    processed    boolean                             NOT NULL,
    retry_count  integer                             NOT NULL,
    created_at   timestamp(6) without time zone      NOT NULL,
    CONSTRAINT dashboard_outbox_pkey PRIMARY KEY (id),
    CONSTRAINT dashboard_outbox_event_type_check CHECK ((event_type::text = ANY (ARRAY['DASHBOARD_UPDATE'::character varying]::text[])))
);

ALTER TABLE dashboard_outbox ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME dashboard_outbox_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE history_outboxes
(
    id          bigint                              NOT NULL,
    type        character varying(255)              NOT NULL,
    payload     text                                NOT NULL,
    processed   boolean                             NOT NULL,
    retry_count integer                             NOT NULL,
    created_at  timestamp(6) without time zone      NOT NULL,
    CONSTRAINT history_outboxes_pkey PRIMARY KEY (id),
    CONSTRAINT history_outboxes_type_check CHECK ((type::text = ANY (ARRAY['PAYMENT'::character varying, 'REFUND'::character varying]::text[])))
);

ALTER TABLE history_outboxes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME history_outboxes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
